Repository mantidproject/mantidimaging, pull requests merged in 2024-11, with the labels that each got.

#2349 2348 Pyright
  .github/workflows/conda.yml
  .github/workflows/windows.yml
  .pre-commit-config.yaml
  Makefile
  docs/release_notes/next/dev-2348-Pyright
  environment-dev.yml
  mantidimaging/core/io/instrument_log.py
  mantidimaging/core/operations/monitor_normalisation/monitor_normalisation.py
  mantidimaging/core/reconstruct/astra_recon.py
  mantidimaging/core/reconstruct/cil_recon.py
  mantidimaging/core/utility/histogram.py
  mantidimaging/core/utility/memory_usage.py
  mantidimaging/core/utility/test/memory_usage_test.py
  mantidimaging/eyes_tests/base_eyes.py
  mantidimaging/eyes_tests/eyes_manager.py
  mantidimaging/gui/dialogs/async_task/presenter.py
  mantidimaging/gui/dialogs/cor_inspection/model.py
  mantidimaging/gui/dialogs/cor_inspection/view.py
  mantidimaging/gui/widgets/auto_colour_menu/auto_color_menu.py
  mantidimaging/gui/widgets/line_profile_plot/view.py
  mantidimaging/gui/widgets/mi_image_view/view.py
  mantidimaging/gui/widgets/mi_mini_image_view/view.py
  mantidimaging/gui/widgets/palette_changer/presenter.py
  mantidimaging/gui/windows/main/view.py
  mantidimaging/gui/windows/nexus_load_dialog/presenter.py
  mantidimaging/gui/windows/operations/filter_previews.py
  mantidimaging/gui/windows/recon/model.py
  mantidimaging/gui/windows/recon/presenter.py
  mantidimaging/gui/windows/spectrum_viewer/spectrum_widget.py
  mantidimaging/gui/windows/spectrum_viewer/view.py
  pyproject.toml
Labels: dependencies, cleanup

#2396 Only Redraw ROI and Subsequently Spectrum if isVisible is True
  docs/release_notes/next/fix-2376-resolve_spectrum_visiblity_when_normalisation_toggled_on_and_off
  mantidimaging/gui/windows/spectrum_viewer/presenter.py
  mantidimaging/gui/windows/spectrum_viewer/test/presenter_test.py
Labels: Type: Bug

#2398 Multiple Live Viewers can be opened simultaneously
  docs/release_notes/next/feature-2361-multiple-live-viewers
  mantidimaging/eyes_tests/live_viewer_window_test.py
  mantidimaging/gui/windows/live_viewer/presenter.py
  mantidimaging/gui/windows/live_viewer/view.py
  mantidimaging/gui/windows/main/view.py
Labels: Type: Improvement

#2403 Move File -> Load 180 Projection to Add / Replace Stack dialog
  mantidimaging/gui/test/gui_system_loading_test.py
  mantidimaging/gui/ui/main_window.ui
  mantidimaging/gui/windows/add_images_to_dataset_dialog/view.py
  mantidimaging/gui/windows/main/model.py
  mantidimaging/gui/windows/main/presenter.py
  mantidimaging/gui/windows/main/test/model_test.py
  mantidimaging/gui/windows/main/test/presenter_test.py
  mantidimaging/gui/windows/main/test/view_test.py
  mantidimaging/gui/windows/main/view.py
Labels: Type: Improvement
