Repository mantidproject/mantidimaging, pull requests merged in 2024-03, with the labels that each got.

#2077 Update Environment Versions to 2.7.0
  environment-dev.yml
  environment.yml
Labels: Release 🚀

#2085 added --run-tests open in pytest
  Makefile
  conftest.py
  docs/release_notes/next/dev-2082-pytest_separation
Labels: Type: Bug, Quality: Testing

#2113 Spectrum Viewer stacks update after Operations
  docs/release_notes/next/fix-2113-spectrum-viewer-sync-stacks
  mantidimaging/gui/windows/spectrum_viewer/presenter.py
Labels: Type: Bug

#2103 Disable no site packages
  .github/workflows/conda.yml
  .github/workflows/cos7_testing.yml
  .github/workflows/u18_testing.yml
  .github/workflows/windows.yml
  .pre-commit-config.yaml
  Makefile
  docs/release_notes/next/dev-2008-mypy-site-packages
  environment-dev.yml
  mantidimaging/eyes_tests/eyes_manager.py
Labels: rebuild_docker 🐋

#2153 fix eyes_test GitHub actions
  .github/workflows/conda.yml
  .github/workflows/windows.yml
Labels: Type: Bug, High Priority
