Repository mantidproject/mantidimaging, pull requests merged in 2024-02, with the labels that each got.

#2026 Resizable tof spectrum viewer
  docs/release_notes/next/feature-2026-resizable-tof-spectrum
  mantidimaging/eyes_tests/spectrum_viewer_test.py
  mantidimaging/gui/windows/spectrum_viewer/presenter.py
  mantidimaging/gui/windows/spectrum_viewer/spectrum_widget.py
  mantidimaging/gui/windows/spectrum_viewer/test/presenter_test.py
  mantidimaging/gui/windows/spectrum_viewer/test/spectrum_test.py
  mantidimaging/gui/windows/spectrum_viewer/view.py
Labels: Type: Improvement

#2064 2062 Spectrum Viewer ROI Desync Fix
  mantidimaging/gui/windows/spectrum_viewer/view.py
Labels: High Priority

#2059 Create Pre-Release Issue Template
  .github/ISSUE_TEMPLATE/release.md
Labels: Type: Improvement

#2079 Flash Review: Resolve Build Docs
  docs/conf.py
Labels: High Priority, Release essential, Release 🚀
