Repository mantidproject/mantidimaging, pull requests merged in 2025-01, with the labels that each got.

#2439 create_dev_env: Only try to remove old dev env if it exists
  docs/release_notes/next/dev-2438-dev-env-fix
  setup.py
Labels: rebuild_docker 🐋

#2441 2397 fits support
  docs/release_notes/next/fix-2397-fix-fits_file_support
  mantidimaging/core/io/loader/loader.py
  mantidimaging/core/io/utility.py
Labels: Type: Bug

#2445 Add the ruff INP001 rule
  docs/release_notes/next/dev-2444-ruff-implicit-namespace-package
  environment-dev.yml
  mantidimaging/gui/widgets/palette_changer/test/__init__.py
  pyproject.toml
Labels: rebuild_docker 🐋

#2461 FLASH PR - Pin Pyright Version to 1.1.391
  environment-dev.yml
Labels: Type: Bug, Quality: Static Analysis

#2462 FLASH PR Refactor How Fits Files are Loaded to Remove String Formatting
  mantidimaging/gui/windows/live_viewer/presenter.py
Labels: cleanup

#2453 2446 update developer guideline docs
  README.md
  docs/developer_guide/explanations/developer_conventions.rst
Labels: Component: Documentation
